### ISSUE TITLE
Upgrade Stampit quality control and security meta

### ISSUE THREAD

**Issue by ericelliott** [stampit-org/stampit#116]
Bring stampit up to the standards laid out in the [prod-module-boilerplate](https://github.com/ericelliott/prod-module-boilerplate/blob/master/README.md#features)

* [x] [Lint with ESLint](https://github.com/stampit-org/stampit/issues/111)
* [x] [Coverage](https://github.com/stampit-org/stampit/issues/115)
* [x] [Ensure dependencies are properly declared in package.json](https://github.com/stampit-org/stampit/issues/118)
* [x] [Dependency security audits with nsp](https://github.com/stampit-org/stampit/issues/117)

**Comment by koresar** [comment]
Done.
